spring:
  datasource:
    url: jdbc:mysql://39.106.1.43:3306/blog
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
server:
  port: 8090
mybatis:
  mapper-locations: classpath:mybatis/*.xml
logging:
  level:
    com.hub.hubback.dao: debug
