spring:
  datasource:
    url: jdbc:mysql://39.106.1.43:3306/blog?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
  redis:
    database: 0
    host: 39.106.1.43
    timeout: 2000
    port: 6379


server:
  port: 8090
mybatis:
  mapper-locations: classpath:mybatis/*.xml
logging:
  level:
    com.hub.hubback.dao: debug
